export const ActionTypes = {
    
  FETCH_ALL_DATA:"FETCH_ALL_DATA",
  
    // FETCH_DATA: "FETCH_DATA",
    // FETCH_DATA_LIST_SUCCESS: "FETCH_DATA_LIST_SUCCESS",
    // FETCH_DATA_LIST_FAILED: "FETCH_DATA_LIST_FAILED",
    // FETCH_DATA_LIST_DELETE: "FETCH_DATA_LIST_DELETE",
    // ADD_TO_DATA_LIST: "ADD_TO_DATA_LIST",
    // SET_DATA_LIST_EDIT: "SET_DATA_LIST_EDIT",
    // SET_DATA_LIST_VIEW: "SET_DATA_LIST_VIEW",
    // FETCH_DATA_RECEIVED: "FETCH_DATA_RECEIVED",

  };